[package]
name = "documentation"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "tuono-documentation"
path = ".tuono/main.rs"

[dependencies]
tuono_lib = "0.17.3"
glob = "0.3.1"
time = { version = "0.3", features = ["macros"] }
serde = { version = "1.0.202", features = ["derive"] }
