services:
  tuono:
    platform: linux/amd64
    container_name: tuono-source-container
    hostname: tuono-source-container
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        RUST_VERSION: 1.83 # if change, think to update the default ARGs in Dockerfile
        BASE_OS: bookworm # if change, think to update the default ARGs in Dockerfile
    image: tuono-source-image
    ports:
      - '3000:3000' # expose default port used by tuono server
    volumes: # mount the project into a volume but node_modules / .pnpm-store / target / ... directories won't by sync from container to host
      - ..:/tuono
      - /tuono/node_modules
      - /tuono/target
      - /tuono/.pnpm-store
      - /tuono/.turbo
      - /tuono/apps/documentation/node_modules
      - /tuono/apps/documentation/target
      - /tuono/examples/tuono-app/node_modules
      - /tuono/examples/tuono-app/target
      - /tuono/examples/tuono-tutorial/node_modules
      - /tuono/examples/tuono-tutorial/target
      - /tuono/examples/with-mdx/node_modules
      - /tuono/examples/with-mdx/target
    tty: true
