name: Documentation Website CI

on:
  push:
    branches:
      - 'main'
    # match
    # - all files inside `apps/documentation` and `.github`
    # - all files in the root expect `Cargo.toml`
    paths:
      - '.github/**'
      - '*'
      - '!Cargo.toml'
      - 'apps/documentation/**'
  pull_request:
    # same as `on.push.paths`
    paths:
      - '.github/**'
      - '*'
      - '!Cargo.toml'
      - 'apps/documentation/**'

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install tuono
        run: cargo install tuono@0.17.3

      - name: Version
        working-directory: ./apps/documentation
        run: |
          tuono --version
          pnpm ls tuono

      - name: Build project
        working-directory: ./apps/documentation
        run: tuono build --static

  code_check:
    name: Check format, lint and types
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Check formatting
        run: pnpm docs:format:check

      - name: Lint
        run: pnpm docs:lint

      - name: Types
        run: pnpm docs:types
